### PR TITLE
#1177: create template repository

### LINKED ISSUE #1177: Create template repository with base workflow configuration
**What Needs to be Done?**

This is sort of a meta-issue..

As we add more repos, we have to manually add the basic Github workflows that do the common checks for signed commits, whitespace, issue #, etc. GitHub has the capability of creating a template repository from which new repos can be created starting with a baseline configuration. Can you create a new repository that will be the template? Once you have it set up, I can make it a template in the GitHub settings.

### PR DESCRIPTION
**Pull request by jstrzebonski**
Fixes DARMA-tasking/vt#1177

### CODE REVIEW

**Comment by jstrzebonski** [comment]
I wonder if we should change rules for PR description in case of cross referencing between projects. @lifflander what do you think?

**Comment by lifflander** [comment]
> I wonder if we should change rules for PR description in case of cross referencing between projects. @lifflander what do you think?

Yes, I think that might make sense given that many of the repos are related. Can you do that before you merge?

**Comment by lifflander** [comment]
This looks good to me. All of the workflows I expected are here!

**Review by lifflander — APPROVED** [review]

**Comment by jstrzebonski** [comment]
Waiting for DARMA-tasking/check-pr-fixes-issue#9 to be fixed

**Pull request merged**
